name: esowc-drought
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - shap
  - python=3.7.3
  - xarray=0.12.3
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - tqdm
  - pytest
  - pytest-flake8
  - pytest-cov
  - mypy=0.720
  - black
  - pip:
    - ray[tune]
    - filelock
