name: esowc
channels:
  - conda-forge
  - defaults
dependencies:
  - apipkg=1.5
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cdsapi=0.1.4
  - certifi=2019.3.9
  - cffi=1.12.3
  - cfgrib=0.9.6.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.6.1
  - cycler=0.10.0
  - eccodes=2.12.3
  - execnet=1.6.0
  - flake8=3.7.7
  - freetype=2.10.0
  - future=0.17.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - idna=2.8
  - jasper=1.900.1
  - jpeg=9c
  - kiwisolver=1.1.0
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libssh2=1.8.2
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mccabe=0.6.1
  - more-itertools=4.3.0
  - mypy=0.701
  - mypy_extensions=0.4.1
  - numpy=1.16.3
  - openblas=0.3.6
  - openssl=1.1.1b
  - pandas=0.24.2
  - pep8=1.7.1
  - pluggy=0.11.0
  - psutil=5.4.8
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pysocks=1.6.8
  - pytest=4.4.2
  - pytest-flake8=1.0.4
  - python-dateutil=2.8.0
  - pytz=2019.1
  - requests=2.21.0
  - six=1.12.0
  - typed-ast=1.3.5
  - urllib3=1.24.2
  - xarray=0.12.1
  - appnope=0.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - curl=7.62.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - libcurl=7.62.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyrsistent=0.14.11
  - pytest-cache=1.0
  - python=3.7.3
  - pyzmq=18.0.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - typing=3.6.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
